"""The AI attribution patterns, declared once, and what is done with them.

The Claude Code harness pushes a "Co-Authored-By" trailer and a "Generated with
Claude Code" line by default. Three layers stand against it, and they fail
differently, which is the reason for having three:

1. the `attribution` setting in `~/.claude/settings.json`, which an update may
   not preserve;
2. a `commit-msg` hook, which prevents at the source but that `--no-verify`
   bypasses and that does not exist in a fresh container;
3. the check in this module, which prevents nothing and cannot be bypassed by
   anything, because it looks at the result.

The patterns live here and the hook is DERIVED from them: two lists would end up
disagreeing on what counts, and the layer that prevents would stop protecting
what the layer that checks refuses.
"""

from __future__ import annotations

import re

# A HUMAN co-author is legitimate: only the lines that name the tool go.
# The `.{0,4}` of the second one lets an emoji or bullet prefix through.
PATTERNS = (
    r"^\s*co-authored-by:.*(claude|anthropic)",
    r"^.{0,4}generated with \[?claude code\]?",
    r"^\s*claude-session:",
)

_MATCHERS = tuple(re.compile(pattern, re.IGNORECASE) for pattern in PATTERNS)


def offending_lines(text: str) -> tuple[str, ...]:
    """The attribution lines present. Empty means clean."""
    return tuple(line for line in text.splitlines()
                 if any(matcher.search(line) for matcher in _MATCHERS))


def strip(text: str) -> str:
    """Remove the offending lines, and nothing else.

    By PATTERN and never by position: deleting "the last line" would destroy a
    legitimate line when there is no trailer. Trailing blank lines go too, but
    not the ones in the middle, which separate paragraphs.
    """
    kept = [line for line in text.splitlines()
            if not any(matcher.search(line) for matcher in _MATCHERS)]
    while kept and not kept[-1].strip():
        kept.pop()
    return "\n".join(kept)


def hook_script() -> str:
    """The `commit-msg` hook, derived from the patterns above.

    It aborts the commit if it cannot run, rather than letting it through
    unfiltered: a guard that goes quiet when it breaks guards nothing.
    """
    alternation = "|".join(
        pattern.replace(r"\s*", "[[:space:]]*").replace(r"\[?", r"\[?").replace(r"\]?", r"\]?")
        for pattern in PATTERNS
    )
    return f"""#!/bin/sh
# Remove any AI attribution from a commit message, wherever it sits.
# GENERATED by forgeron from attribution.PATTERNS: do not edit by hand, the
# patterns live in forgeron/attribution.py and the check uses the same ones.
set -eu

msg="${{1:-}}"
[ -n "$msg" ] && [ -f "$msg" ] || exit 0

motif='{alternation}'

tmp=$(mktemp) || exit 1
trap 'rm -f "$tmp"' EXIT

grep -viE "$motif" "$msg" > "$tmp" || true
awk '{{l[NR]=$0}} END{{n=NR; while (n>0 && l[n] ~ /^[[:space:]]*$/) n--; \
for (i=1;i<=n;i++) print l[i]}}' "$tmp" > "$msg"
"""
