name: Release

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: MasterLaplace/.github/actions/release@693ec5b0153d2fc72232aa6dc78a6eaaa5b3bea8 # main
        with:
          config-header: CITATION.cff

  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    concurrency: release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: MasterLaplace/.github/actions/release@693ec5b0153d2fc72232aa6dc78a6eaaa5b3bea8 # main
        with:
          config-header: CITATION.cff
